#!/usr/bin/perl
use strict;
use warnings;

use POSIX;
use Getopt::Long qw/:config bundling/;
our %OPTIONS = ();
GetOptions(\%OPTIONS, qw/
	help|h|?
	debug|D

	host|H=s
/);
chomp($OPTIONS{host} = qx(hostname -f))
	unless $OPTIONS{host};

open my $pipe, "-|", "/bin/df -lT"
	or exit 1;
<$pipe>;
while (<$pipe>) {
	chomp;
	my ($dev, $fs, $size, $used, $free, undef, $path) = split(/\s+/, $_, 7);
	next if $fs eq 'none';
	next if $fs =~ m/tmpfs$/;

	my $now = time;
	printf "SAMPLE %i %s:bytes:%s:total %0.3f\n", $state, $path, $size * 1024;
	printf "SAMPLE %i %s:bytes:%s:used %0.3f\n",  $state, $path, $used * 1024;
	printf "SAMPLE %i %s:bytes:%s:free %0.3f\n",  $state, $path, $free * 1024;
	printf "SAMPLE %i %s:bytes:%s:util %0.3f\n",  $state, $path, $used / $size;
}
close $pipe;

open $pipe, "-|", "/bin/df -lT -i"
	or exit 1;
<$pipe>;
while (<$pipe>) {
	chomp;
	my ($dev, $fs, $size, $used, $free, undef, $path) = split(/\s+/, $_, 7);
	next if $fs eq 'none';
	next if $fs =~ m/tmpfs$/;

	my $now = time;
	printf "SAMPLE %i %s:inodes:%s:total %0.3f\n", $state, $path, $size * 1024;
	printf "SAMPLE %i %s:inodes:%s:used %0.3f\n",  $state, $path, $used * 1024;
	printf "SAMPLE %i %s:inodes:%s:free %0.3f\n",  $state, $path, $free * 1024;
	printf "SAMPLE %i %s:inodes:%s:util %0.3f\n",  $state, $path, $used / $size;
}
close $pipe;
exit 0;
