#!/usr/bin/perl

sub usage
{
	print <<EOF;
hostinfo (a Bolo collector)
USAGE: hostinfo [options]

options:
   -h, --help               Show this help screen
   -p, --prefix PREFIX      Use the given metric prefix
                            (FQDN is used by default)

EOF
	exit 0;
}

use POSIX;
use Getopt::Long qw/:config bundling/;
our %OPTIONS = (
	prefix => $ENV{DBOLO_PREFIX},
);
GetOptions(\%OPTIONS, qw/
	help|h|?

	prefix|p=s
/) or usage();
usage() if $OPTIONS{help};
chomp($OPTIONS{prefix} = qx(hostname -f))
	unless $OPTIONS{prefix};

open my $fh, "<", "/etc/mtab"
	or die "failed to open /etc/mtab: $!\n";

print "KEY $OPTIONS{prefix}:host\n";
while (<$fh>) {
	next unless m{^/};
	my ($dev, $path) = split ' ';

	print "KEY $OPTIONS{prefix}:fs:$path\n";
	print "KEY $OPTIONS{prefix}:dev:$dev\n";
}
close $fh;
