#!/usr/bin/perl

chomp(my $fqdn = qx(hostname -f));
open my $fh, "<", "/etc/mtab"
	or die "failed to open /etc/mtab: $!\n";

print "KEY $fqdn:host\n";
while (<$fh>) {
	next unless m{^/};
	my ($dev, $path) = split ' ';

	print "KEY $fqdn:fs:$path\n";
	print "KEY $fqdn:dev:$dev\n";
}
close $fh;
