#!/usr/bin/perl
use strict;
use warnings;

use Getopt::Long qw/:config bundling/;
our %OPTIONS = ();
GetOptions(\%OPTIONS, qw/
	help|h|?
	debug|D

	host|H=s
/);
chomp($OPTIONS{host} = qx(hostname -f))
	unless $OPTIONS{host};

my $state = "$OPTIONS{host}:openfiles";

open my $fh, "<", $ENV{TEST_OPENFILES_STATS} || "/proc/sys/fs/file-nr"
	or exit 0;
chomp(local $_ = <$fh>);
my ($used, $free, $max) = split /\s+/;

my $now = time;
printf "SAMPLE %i %s:used %i\n", $now, $state, $used;
printf "SAMPLE %i %s:free %i\n", $now, $state, $free;
printf "SAMPLE %i %s:max %i\n",  $now, $state, $max;
exit 0;
